include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat deprecations, async-context hints and const-suggestions as non-failing.
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    prefer_const_constructors: ignore
    prefer_const_declarations: ignore

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # Style rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    camel_case_extensions: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
